id: 8
source: 2
type: number
name: productPrice
caption: Preis
category: Shop
elements: ''
rank: 20
display: default
default_text: ''
properties: 'a:0:{}'
input_properties: 'a:7:{s:10:"allowBlank";s:4:"true";s:13:"allowDecimals";s:4:"true";s:13:"allowNegative";s:5:"false";s:16:"decimalPrecision";s:1:"2";s:16:"decimalSeparator";s:1:",";s:8:"maxValue";s:0:"";s:8:"minValue";s:0:"";}'
output_properties: 'a:0:{}'
content: ''
