id: 10
source: 2
type: text
name: productOverlay
caption: Overlay-Text
category: Grafiken
elements: 'Rot==color1||Pink==color2||Grün==color3||Gelb==color4||Rosa==#fbb1b0||Orange==#ff7000'
rank: 17
display: default
properties: 'a:0:{}'
input_properties: 'a:5:{s:10:"allowBlank";s:4:"true";s:9:"minLength";s:0:"";s:9:"maxLength";s:0:"";s:5:"regex";s:0:"";s:9:"regexText";s:0:"";}'
output_properties: 'a:3:{s:14:"phpThumbParams";s:6:"w=1000";s:11:"outputChunk";s:0:"";s:11:"generateUrl";s:4:"true";}'

-----

BUY NOW!