id: 6
source: 2
type: migx
name: productSliderWrapper
caption: 'Weitere Produktbilder'
category: Grafiken
elements: ''
rank: 30
display: default
default_text: ''
properties: 'a:0:{}'
input_properties: 'a:7:{s:7:"configs";s:20:"productsliderwrapper";s:8:"formtabs";s:0:"";s:7:"columns";s:0:"";s:7:"btntext";s:23:"Produktbild hinzufügen";s:10:"previewurl";s:0:"";s:10:"jsonvarkey";s:0:"";s:19:"autoResourceFolders";s:5:"false";}'
output_properties: 'a:0:{}'
content: ''
