id: 19
source: 2
type: listbox
name: productButtonPosition
caption: 'Position Button'
category: Shop
elements: 'Unten rechts==--bottomRight||Oben rechts==--topRight||Unten links==--bottomLeft||Oben links==--topLeft'
rank: 40
display: default
properties: 'a:0:{}'
input_properties: 'a:7:{s:10:"allowBlank";s:5:"false";s:9:"listWidth";s:0:"";s:5:"title";s:0:"";s:9:"typeAhead";s:5:"false";s:14:"typeAheadDelay";s:3:"250";s:14:"forceSelection";s:5:"false";s:13:"listEmptyText";s:0:"";}'
output_properties: 'a:0:{}'

-----

--bottomRight